# Generated by Django 3.2.15 on 2022-08-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20220810_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
    ]
