# Generated by Django 3.2.15 on 2022-08-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='time_created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
    ]
