# Generated by Django 3.2.15 on 2022-08-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_alter_feedback_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
    ]
