# Generated by Django 3.2.15 on 2022-08-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_feedback_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
